[package]
name = "fpp-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fpp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.3", features = ["cargo"] }
fpp-compiler = { path = "../compiler" }
messages = { path = "../messages" }
